package config

import (
	"os"
	"path/filepath"
	"testing"

	"project-tachyon/internal/storage"
)

// newTestConfig creates a ConfigManager backed by a temp SQLite DB.
func newTestConfig(t *testing.T) *ConfigManager {
	t.Helper()
	tmpDir := t.TempDir()
	dbPath := filepath.Join(tmpDir, "test.db")

	// Open storage directly with temp DB path
	s, err := storage.NewStorageWithPath(dbPath)
	if err != nil {
		t.Fatalf("failed to create test storage: %v", err)
	}
	t.Cleanup(func() { s.Close() })

	return NewConfigManager(s)
}

func TestConfigManager_AIPortDefault(t *testing.T) {
	cfg := newTestConfig(t)
	if cfg.GetAIPort() != 4444 {
		t.Fatalf("expected default port 4444, got %d", cfg.GetAIPort())
	}
}

func TestConfigManager_SetGetAIPort(t *testing.T) {
	cfg := newTestConfig(t)
	if err := cfg.SetAIPort(9090); err != nil {
		t.Fatal(err)
	}
	if cfg.GetAIPort() != 9090 {
		t.Fatalf("expected port 9090, got %d", cfg.GetAIPort())
	}
}

func TestConfigManager_MaxConcurrentDefault(t *testing.T) {
	cfg := newTestConfig(t)
	if cfg.GetAIMaxConcurrent() != 5 {
		t.Fatalf("expected default 5, got %d", cfg.GetAIMaxConcurrent())
	}
}

func TestConfigManager_SetGetMaxConcurrent(t *testing.T) {
	cfg := newTestConfig(t)
	if err := cfg.SetAIMaxConcurrent(10); err != nil {
		t.Fatal(err)
	}
	if cfg.GetAIMaxConcurrent() != 10 {
		t.Fatalf("expected 10, got %d", cfg.GetAIMaxConcurrent())
	}
}

func TestConfigManager_EnableAI(t *testing.T) {
	cfg := newTestConfig(t)
	// Default is false
	if cfg.GetEnableAI() {
		t.Fatal("expected AI disabled by default")
	}
	if err := cfg.SetEnableAI(true); err != nil {
		t.Fatal(err)
	}
	if !cfg.GetEnableAI() {
		t.Fatal("expected AI enabled after set")
	}
}

func TestConfigManager_IntegrityCheckDefault(t *testing.T) {
	cfg := newTestConfig(t)
	if !cfg.GetEnableIntegrityCheck() {
		t.Fatal("expected integrity check enabled by default")
	}
}

func TestConfigManager_TokenAutoGenerated(t *testing.T) {
	cfg := newTestConfig(t)
	token := cfg.GetAIToken()
	if len(token) < 16 {
		t.Fatalf("expected auto-generated token, got %q", token)
	}
	// Should be stable
	if cfg.GetAIToken() != token {
		t.Fatal("token should be stable across calls")
	}
}

func TestConfigManager_UserAgentEmpty(t *testing.T) {
	cfg := newTestConfig(t)
	ua := cfg.GetUserAgent()
	if ua != "" {
		t.Fatalf("expected empty user agent by default, got %q", ua)
	}
}

// Suppress unused import warning
var _ = os.DevNull
